---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: kinoite-zfs
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # follow the default Kinoite stream

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: containerfile
    snippets:
      - |
        RUN bash -euxo pipefail <<'EOF'
        FEDORA_VERSION="$(rpm -E %fedora)"
        AKMODS_IMAGE="ghcr.io/danathar/akmods-zfs:main-${FEDORA_VERSION}"

        skopeo copy --retry-times 3 "docker://${AKMODS_IMAGE}" dir:/tmp/akmods-zfs

        mapfile -t layer_files < <(find /tmp/akmods-zfs -maxdepth 1 -type f ! -name manifest.json ! -name version | sort)
        if [[ "${#layer_files[@]}" -eq 0 ]]; then
          echo "No layers found in ${AKMODS_IMAGE}" >&2
          exit 1
        fi
        for layer in "${layer_files[@]}"; do
          tar -xf "${layer}" -C /tmp/
        done

        mapfile -t zfs_rpms < <(
          find /tmp/rpms/kmods/zfs -maxdepth 1 -type f -name '*.rpm' \
            ! -name '*.src.rpm' \
            ! -name '*-debug*' \
            ! -name '*-devel*' \
            ! -name '*-test*' \
            | sort
        )

        if [[ "${#zfs_rpms[@]}" -eq 0 ]]; then
          echo "No ZFS RPMs found in ${AKMODS_IMAGE}" >&2
          exit 1
        fi

        rpm-ostree install "${zfs_rpms[@]}"
        EOF

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
