from __future__ import annotations

from ci_tools.common import (
    CiToolError,
    normalize_owner,
    require_env,
    skopeo_copy,
    skopeo_exists,
    skopeo_inspect_digest,
)


def main() -> None:
    # Inputs from workflow context and job env.
    # Normalize owner means: convert to lowercase for consistent registry paths.
    image_org = normalize_owner(require_env("GITHUB_REPOSITORY_OWNER"))
    registry_actor = require_env("REGISTRY_ACTOR")
    registry_token = require_env("REGISTRY_TOKEN")
    fedora_version = require_env("FEDORA_VERSION")
    image_name = require_env("IMAGE_NAME")
    candidate_akmods_repo = require_env("CANDIDATE_AKMODS_REPO")
    stable_akmods_repo = require_env("STABLE_AKMODS_REPO")
    run_number = require_env("GITHUB_RUN_NUMBER")
    sha_short = require_env("GITHUB_SHA")[:7]

    # Registry credentials format expected by skopeo.
    creds = f"{registry_actor}:{registry_token}"

    # Candidate image tag generated by BlueBuild for this run.
    candidate_source_tag = f"{sha_short}-{fedora_version}"
    # Start from candidate tag (<sha>-<fedora>) and resolve it to a digest.
    candidate_image_by_tag = f"docker://ghcr.io/{image_org}/{image_name}:{candidate_source_tag}"
    candidate_image_digest = skopeo_inspect_digest(candidate_image_by_tag, creds=creds)
    if not candidate_image_digest:
        raise CiToolError(f"Failed to resolve candidate image digest from {candidate_image_by_tag}")

    # Promote by digest so stable tags point to one exact image.
    candidate_image = f"docker://ghcr.io/{image_org}/{image_name}@{candidate_image_digest}"
    stable_image = f"docker://ghcr.io/{image_org}/{image_name}:latest"
    audit_image = f"docker://ghcr.io/{image_org}/{image_name}:stable-{run_number}-{sha_short}"

    skopeo_copy(candidate_image, stable_image, creds=creds)
    skopeo_copy(candidate_image, audit_image, creds=creds)

    # Candidate/stable akmods tags for the same Fedora stream.
    candidate_akmods = f"docker://ghcr.io/{image_org}/{candidate_akmods_repo}:main-{fedora_version}"
    stable_akmods = f"docker://ghcr.io/{image_org}/{stable_akmods_repo}:main-{fedora_version}"

    # Prefer candidate cache, but keep stable fallback for older paths.
    if skopeo_exists(candidate_akmods, creds=creds):
        source_akmods = candidate_akmods
    elif skopeo_exists(stable_akmods, creds=creds):
        source_akmods = stable_akmods
        print("Candidate akmods tag missing; using stable akmods tag as promotion source.")
    else:
        raise CiToolError(f"Neither candidate nor stable akmods tag exists for Fedora {fedora_version}.")

    # Skip unnecessary copy when fallback already equals destination.
    if source_akmods != stable_akmods:
        skopeo_copy(source_akmods, stable_akmods, creds=creds)
    else:
        print(f"Akmods source already at stable tag {stable_akmods}; skipping retag copy.")

    print(f"Resolved candidate source {candidate_image_by_tag} -> {candidate_image}")
    print(f"Promoted {candidate_image} -> {stable_image}")
    print(f"Published audit tag {audit_image}")
    print(f"Promoted {source_akmods} -> {stable_akmods}")


if __name__ == "__main__":
    main()
