from __future__ import annotations

from ci_tools.common import (
    CiToolError,
    normalize_owner,
    require_env,
    skopeo_copy,
    skopeo_inspect_digest,
)


def main() -> None:
    # Inputs from workflow context and job env.
    # Normalize owner means: convert to lowercase for consistent registry paths.
    image_org = normalize_owner(require_env("GITHUB_REPOSITORY_OWNER"))
    registry_actor = require_env("REGISTRY_ACTOR")
    registry_token = require_env("REGISTRY_TOKEN")
    fedora_version = require_env("FEDORA_VERSION")
    candidate_image_name = require_env("CANDIDATE_IMAGE_NAME")
    image_name = require_env("IMAGE_NAME")
    candidate_akmods_repo = require_env("CANDIDATE_AKMODS_REPO")
    stable_akmods_repo = require_env("STABLE_AKMODS_REPO")
    run_number = require_env("GITHUB_RUN_NUMBER")
    sha_short = require_env("GITHUB_SHA")[:7]

    # Registry credentials format expected by skopeo.
    creds = f"{registry_actor}:{registry_token}"

    # Candidate image tag generated by BlueBuild for this run.
    candidate_source_tag = f"{sha_short}-{fedora_version}"
    # Start from candidate repository tag (<sha>-<fedora>) and resolve it to digest.
    candidate_image_by_tag = (
        f"docker://ghcr.io/{image_org}/{candidate_image_name}:{candidate_source_tag}"
    )
    candidate_image_digest = skopeo_inspect_digest(candidate_image_by_tag, creds=creds)
    if not candidate_image_digest:
        raise CiToolError(f"Failed to resolve candidate image digest from {candidate_image_by_tag}")

    # Promote by digest so stable tags point to one exact image snapshot.
    candidate_image = f"docker://ghcr.io/{image_org}/{candidate_image_name}@{candidate_image_digest}"
    stable_image = f"docker://ghcr.io/{image_org}/{image_name}:latest"
    audit_image = f"docker://ghcr.io/{image_org}/{image_name}:stable-{run_number}-{sha_short}"

    skopeo_copy(candidate_image, stable_image, creds=creds)
    skopeo_copy(candidate_image, audit_image, creds=creds)

    # Candidate/stable akmods tags for the same Fedora stream.
    candidate_akmods = f"docker://ghcr.io/{image_org}/{candidate_akmods_repo}:main-{fedora_version}"
    stable_akmods = f"docker://ghcr.io/{image_org}/{stable_akmods_repo}:main-{fedora_version}"

    # Promote from candidate akmods only.
    # "Fail closed" here means: stop with an explicit error if candidate akmods
    # are missing, instead of silently falling back to stable akmods.
    # This protects stable tags from being advanced with stale module content.
    candidate_akmods_digest = skopeo_inspect_digest(candidate_akmods, creds=creds)
    if not candidate_akmods_digest:
        raise CiToolError(
            f"Failed to resolve candidate akmods digest from {candidate_akmods}"
        )
    skopeo_copy(candidate_akmods, stable_akmods, creds=creds)

    print(f"Resolved candidate source {candidate_image_by_tag} -> {candidate_image}")
    print(f"Promoted candidate image {candidate_image} -> stable {stable_image}")
    print(f"Published audit tag {audit_image}")
    print(f"Resolved candidate akmods source {candidate_akmods}@{candidate_akmods_digest}")
    print(f"Promoted {candidate_akmods} -> {stable_akmods}")


if __name__ == "__main__":
    main()
